---
services:
  demo: ~
  tms:
    use_grid_names: true
    origin: nw
  kml:
    use_grid_names: true
  wmts: ~
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.
layers:
- name: usa
  title: Layer usa
  sources:
  - usa_cache
- name: geotiff
  title: Layer 20
  sources:
  - geotiff_cache
- name: monarchs
  title: Layer monarchs
  sources:
  - monarchs_cache
- name: CustomDemo
  title: Layer CustomDemo
  sources:
  - CustomDemo_cache
- name: nws
  title: Layer nws
  sources:
  - nws_cache
- name: bgsgrid.GB_Hex_5km_GS_SolubleRocks_v8
  title: Layer bgsgrid.GB_Hex_5km_GS_SolubleRocks_v8
  sources:
  - bgsgrid.GB_Hex_5km_GS_SolubleRocks_v8_cache
- name: bgsgrid.GB_Hex_5km_GS_RunningSand_v8
  title: Layer bgsgrid.GB_Hex_5km_GS_RunningSand_v8
  sources:
  - bgsgrid.GB_Hex_5km_GS_RunningSand_v8_cache
- name: neighborhoods.neighborhoods
  title: Layer neighborhoods.neighborhoods
  sources:
  - neighborhoods.neighborhoods_cache
- name: neighborhoods.parks
  title: Layer neighborhoods.parks
  sources:
  - neighborhoods.parks_cache
- name: neighborhoods.waterways
  title: Layer neighborhoods.waterways
  sources:
  - neighborhoods.waterways_cache
- name: qfieldSimpleBee.Fields
  title: Layer qfieldSimpleBee.Fields
  sources:
  - qfieldSimpleBee.Fields_cache
- name: qfieldSimpleBee.Apiary
  title: Layer qfieldSimpleBee.Apiary
  sources:
  - qfieldSimpleBee.Apiary_cache
- name: qfieldSimpleBee.Tracks
  title: Layer qfieldSimpleBee.Tracks
  sources:
  - qfieldSimpleBee.Tracks_cache
- name: paris1550
  title: Layer paris1550
  sources:
  - paris1550_cache
caches:
  usa_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - usa
  geotiff_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - geotiff
  customdemo_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - CustomDemo
  monarchs_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - monarchs
  qfieldsimplebee_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - qfieldSimpleBee
  CustomDemo_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - CustomDemo
  nws_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - nws
  bgsgrid.GB_Hex_5km_GS_SolubleRocks_v8_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - bgsgrid.GB_Hex_5km_GS_SolubleRocks_v8
  bgsgrid.GB_Hex_5km_GS_RunningSand_v8_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - bgsgrid.GB_Hex_5km_GS_RunningSand_v8
  neighborhoods.neighborhoods_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - neighborhoods.neighborhoods
  neighborhoods.parks_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - neighborhoods.parks
  neighborhoods.waterways_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - neighborhoods.waterways
  qfieldSimpleBee.Fields_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - qfieldSimpleBee.Fields
  qfieldSimpleBee.Apiary_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - qfieldSimpleBee.Apiary
  qfieldSimpleBee.Tracks_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - qfieldSimpleBee.Tracks
  paris1550_cache:
    grids:
    - webmercator
    request_format: image/png
    format: image/png
    sources:
    - paris1550
sources:
  usa:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F2%2Fusdemo.qgs
      layers: states
      transparent: true
  geotiff:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F4%2Fusgeotiff.qgs
      layers: topp-states
      transparent: true
  CustomDemo:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F2%2Fusdemo.qgs
      layers: states
      transparent: true
  monarchs:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F7%2Fmonarch-habitats.qgs
      layers: "S_USA.Activity_MBHR_PL \u2014 Activity_MBHR_PL"
      transparent: true
  nws:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F6%2Fweather-service.qgs
      layers: NDFD Forecast hawaii.apparentt,NDFD Forecast hawaii.apparentt.points
      transparent: true
  bgsgrid.GB_Hex_5km_GS_SolubleRocks_v8:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F4%2Fbgsgrid.qgs
      layers: GB_Hex_5km_GS_SolubleRocks_v8
      transparent: true
  bgsgrid.GB_Hex_5km_GS_RunningSand_v8:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F4%2Fbgsgrid.qgs
      layers: GB_Hex_5km_GS_RunningSand_v8
      transparent: true
  neighborhoods.neighborhoods:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F3%2Fchicago.qgs
      layers: neighborhoods
      transparent: true
  neighborhoods.parks:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F3%2Fchicago.qgs
      layers: parks
      transparent: true
  neighborhoods.waterways:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F3%2Fchicago.qgs
      layers: waterways
      transparent: true
  qfieldSimpleBee.Fields:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F8%2Fbees.qgs
      layers: Fields
      transparent: true
  qfieldSimpleBee.Apiary:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F8%2Fbees.qgs
      layers: Apiary
      transparent: true
  qfieldSimpleBee.Tracks:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F8%2Fbees.qgs
      layers: Tracks
      transparent: true
  paris1550:
    type: wms
    req:
      url: http://localhost/cgi-bin/qgis_mapserv.fcgi?VERSION=1.1.0&map=%2Fvar%2Fwww%2Fdata%2Fstores%2F5%2Fparis.qgs
      layers: paris
      transparent: true
grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR
globals:
  image:
    formats:
      imgformat:
        format: image/png
        mode: P
        transparent: true
...
